// Generated by CoffeeScript 1.9.0
(function() {
  var baseArea, idealWinW, keyFrames, mapValueInRange, minWinW, resizeHandler, scale, winScale, winW;

  baseArea = 1152000;

  idealWinW = 1440;

  minWinW = 320;

  winW = null;

  resizeHandler = function(e) {
    var winH;
    console.log("resize");
    winH = window.innerHeight;
    winW = window.innerWidth;
    return scale(winW);
  };

  keyFrames = [
    {
      position: 1440,
      value: 18
    }, {
      position: 769,
      value: 12
    }, {
      position: 768,
      value: 18
    }, {
      position: 500,
      value: 18
    }, {
      position: 320,
      value: 12
    }
  ];

  mapValueInRange = function(value, fromLow, fromHigh, toLow, toHigh) {
    var fromRangeSize, toRangeSize, valueScale;
    fromRangeSize = fromHigh - fromLow;
    toRangeSize = toHigh - toLow;
    valueScale = (value - fromLow) / fromRangeSize;
    return toLow + (valueScale * toRangeSize);
  };

  winScale = function(value, from, to) {
    var boundValue;
    boundValue = Math.min(Math.max(value, minWinW), idealWinW);
    return mapValueInRange(boundValue, minWinW, idealWinW, from, to);
  };

  scale = function(winW) {
    var scaleFactor;
    scaleFactor = Math.max(1, winW / idealWinW);
    console.log(scaleFactor, winW, idealWinW);
    return engine.solve({
      'small-font-size': winScale(winW, 14, 18),
      'medium-font-size': winScale(winW, 14, 18),
      'big-font-size': winScale(winW, 16, 24)
    });
  };

  resizeHandler();

  window.addEventListener('resize', resizeHandler);

}).call(this);
